name: Compilação do PDF

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*'

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código
        uses: actions/checkout@v3

      - name: Compilando latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report.tex

      - name: Renomeando o PDF
        run: mv report.pdf report-${{github.ref_name}}.pdf

      - name: Publicando PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: report-${{github.ref_name}}.pdf